<?php

namespace App\Console\Commands;

use App\Models\User;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

#[Signature('topgrade:reset-admin {email? : Administrator email to reset or create} {--password= : Explicit password to set (auto-generates random password if omitted)} {--club : Target primary club admin instead of technical super admin}')]
#[Description('Reset or auto-generate credentials for TopGrade administrator accounts.')]
class ResetAdminPasswordCommand extends Command
{
    /**
     * The command aliases.
     *
     * @var array<int, string>
     */
    protected $aliases = ['topgrade:admin-password'];

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $isClub = (bool) $this->option('club');

        if ($isClub) {
            $email = (string) ($this->argument('email') ?: config('topgrade.admin.email', 'info@topgradelondonfc.co.uk'));
            $name = (string) config('topgrade.admin.name', 'TopGrade Club Admin');
            $isSystem = false;
        } else {
            $email = (string) ($this->argument('email') ?: config('topgrade.dev_admin.email', 'tomc@trupabranding.com'));
            $name = (string) config('topgrade.dev_admin.name', 'Technical Super Admin');
            $isSystem = true;
        }

        $password = (string) $this->option('password');
        $autoGenerated = false;

        if (empty($password)) {
            $password = 'TGFC-'.Str::random(4).'-'.Str::random(4).'-'.Str::random(4);
            $autoGenerated = true;
        }

        $user = User::where('email', $email)->first();

        if ($user) {
            $user->forceFill([
                'password' => Hash::make($password),
                'is_admin' => true,
                'is_system_account' => $isSystem,
                'email_verified_at' => $user->email_verified_at ?? now(),
            ])->save();
        } else {
            $user = User::create([
                'name' => $name,
                'email' => $email,
                'password' => Hash::make($password),
                'is_admin' => true,
                'is_system_account' => $isSystem,
                'email_verified_at' => now(),
            ]);
        }

        if ($isSystem && $email !== 'dev@trupabranding.com') {
            User::where('email', 'dev@trupabranding.com')->delete();
        }

        $this->newLine();
        $this->info('========================================================');
        $this->info('TopGrade London FC - Administrator Credentials Ready');
        $this->line('Role:     <comment>'.($isSystem ? 'Technical Super Admin (Break-Glass)' : 'Club Administrator').'</comment>');
        $this->line("Email:    <comment>{$user->email}</comment>");
        $this->line("Password: <fg=green;options=bold>{$password}</>");
        if ($autoGenerated) {
            $this->warn('NOTE: Password was auto-generated. Copy and store this securely.');
        }
        $this->line('Login at: <comment>'.url('/login').'</comment>');
        $this->info('========================================================');
        $this->newLine();

        return self::SUCCESS;
    }
}
